[project]
name = "fzuhelper-bot"
version = "0.1.1"
description = "fzuhelper-bot"
readme = "README.md"
requires-python = ">=3.10, <4.0"
dependencies = [
    "aiohttp>=3.14.0",
    "aiosmtplib>=5.1.0",
    "asconnect>=3.0.6",
    "cachetools>=7.0.5",
    "cryptography>=40,<47",
    "nb-cli>=1.7.2",
    "nonebot-adapter-milky>=1.2.0",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot2[fastapi,httpx]>=2.4.4",
    "pydantic>=2.0",
    "pyjwt>=2.0.0,<3.0.0",
]

[tool.nonebot]
plugin_dirs = ["src/plugins"]
builtin_plugins = []
[tool.nonebot.plugins]
"@local" = []


[tool.nonebot.adapters]
"@local" = []
nonebot-adapter-milky = [{ name = "nonebot-adapter-milky", module_name = "nonebot.adapters.milky" }]
