services:
  nonebot:
    image: ghcr.io/west2-online/fzuhelper-bot:edge
    # build:
    #  context: .
    #  dockerfile: docker/Dockerfile
    container_name: fzuhelper-bot
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot-network

  lagrange:
    image: ghcr.io/lagrangedev/lagrange.milky:main
    container_name: lagrange
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    user: root
    volumes:
      - ./data:/root
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge