services:
  nonebot:
    image: ghcr.io/west2-online/fzuhelper-bot:edge
    # build:
    #  context: .
    #  dockerfile: docker/Dockerfile
    container_name: fzuhelper-bot
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped